# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "loggability", "~>0.7"

gem "hoe-mercurial", "~>1.4.0", :group => [:development, :test]
gem "hoe-highline", "~>0.1.0", :group => [:development, :test]
gem "rdoc", "~>4.0", :group => [:development, :test]
gem "hoe-deveiate", "~>0.3", :group => [:development, :test]
gem "hoe-bundler", "~>1.2", :group => [:development, :test]
gem "linkparser", "~>1.1", :group => [:development, :test]
gem "wordnet", "~>1.0", :group => [:development, :test]
gem "wordnet-defaultdb", "~>1.0", :group => [:development, :test]
gem "ruby-stemmer", "~>0.9", :group => [:development, :test]
gem "hoe", "~>3.7", :group => [:development, :test]

# vim: syntax=ruby
